---
version: '3.8'
name: 'changedetection'
services:

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    container_name: changedetection
    hostname: changedetection
    env_file: ${PWD}/.env
    volumes:
     - ${PWD}/datastore:/datastore
    ports:
     - ${PORT}:5000
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
    restart: always
    depends_on:
      playwright-chrome:
       condition: service_started
    labels:
      - com.centurylinklabs.watchtower.enable=true

  playwright-chrome:
    image: browserless/chrome
    hostname: playwright-chrome
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 3000:3000
    environment:
     - SCREEN_WIDTH=1920
     - SCREEN_HEIGHT=1024
     - SCREEN_DEPTH=16
     - ENABLE_DEBUGGER=false
     - PREBOOT_CHROME=true
     - CONNECTION_TIMEOUT=300000
     - MAX_CONCURRENT_SESSION=10
     - CHROME_REFRESH_TIME=600000
     - DEFAULT_BLOCK_ADS=true
     - DEFAULT_STEALTH=true
     - DEFAULT_IGNORE_HTTPS_ERRORS=true
