---
version: '3.9'
name: books
services:

  webdav:
    image: bytemark/webdav
    restart: always
    env_file: ${PWD}/.env
    ports:
      - ${WEBDAV_PORT}:80
    volumes:
      - ${PWD}/books:/var/lib/dav
      - ${PWD}/user.passwd:/user.passwd

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    env_file: ${PWD}/.env
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/books/data:/books
    ports:
      - ${BOOKS_PORT}:8083
    restart: always

  nettalk:
    image: cptactionhank/netatalk:latest
    restart: always
    network_mode: "host"
    env_file: ${PWD}/.env
    volumes:
      - ${PWD}/afp.conf:/etc/afp.conf
      - ${PWD}/books/data:/books
