---
# version: "3"
name: 'wg-easy'
services:
  wg-easy:
    image: babadzhanyan/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file: ${PWD}/.env
    volumes:
      - ${PWD}/.wg-easy:/etc/wireguard
    ports:
      - ${WG_PORT}:${WG_PORT}/udp
      - ${PORT}:${PORT}/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
