---
version: "3.9"
name: gotify

services:
    gotify:
        image: ghcr.io/gotify/server
        restart: always
        env_file: ${PWD}/.env
        volumes:
            - ${PWD}/data:/app/data:z
            - ${PWD}/config.yml:/etc/gotify/config.yml
        ports:
            - ${SERVER_PORT}:80
        labels:
            - com.centurylinklabs.watchtower.enable=true
