---
#version: '3.9'
name: "keycloak"

services:

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    env_file: ${PWD}/.env
    volumes:
      - ${PWD}/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    labels:
      - wud.watch=false


  keycloak:
    container_name: keycloak
    depends_on:
      - postgres
    env_file: ${PWD}/.env
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    restart: always
