---
version: '3.4'
name: 'speedtest'
services:

  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - ${PORT_80}:80
      - ${PORT_443}:443
    env_file: ${PWD}/.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${PWD}/app:/config
      - ${PWD}/web:/etc/ssl/web
    # image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    image: 'lscr.io/linuxserver/speedtest-tracker:latest'
    restart: always
    depends_on:
      - db
    labels:
      - com.centurylinklabs.watchtower.enable=true

  db:
    image: mariadb:10
    restart: always
    env_file: ${PWD}/.env
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ${PWD}/db:/var/lib/mysql
    labels:
      - wud.watch=false
