---
version: '3.8'
name: 'speedtest'
services:

  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - ${PORT_80}:80
      - ${PORT_443}:443
    env_file: ${PWD}/.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PUID=1000
      - PGID=1000
      - APP_NAME=Speedtest
      - APP_URL=${APP_URL}
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
      - DISPLAY_TIMEZONE=${DISPLAY_TIMEZONE}
      - PUBLIC_DASHBOARD=true
      - PRUNE_RESULTS_OLDER_THAN=${PRUNE_RESULTS_OLDER_THAN}
      - SPEEDTEST_PING_URL=8.8.8.8
    volumes:
      - ${PWD}/app:/config
      - ${PWD}/web:/etc/ssl/web
    # image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    image: 'lscr.io/linuxserver/speedtest-tracker:latest'
    restart: always
    depends_on:
      - db
    labels:
      - com.centurylinklabs.watchtower.enable=true

  db:
    image: mariadb:10
    restart: always
    env_file: ${PWD}/.env
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ${PWD}/db:/var/lib/mysql
    labels:
      - wud.watch=false
