version: '3.4'
name: nextcloud
services:

  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    env_file: ${PWD}/.env
    volumes:
      - ./db:/var/lib/mysql
    labels:
      - wud.watch=false

  redis:
    image: redis
    restart: always
    env_file: ${PWD}/.env

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    build: ${PWD}/
    env_file: ${PWD}/.env
    ports:
      - ${WEB_PORT}:80
    links:
      - db
      - redis
    volumes:
      - ${PWD}/data:/var/www/html:z
      - ${NEXTCLOUD_DATA_DIR}:${NEXTCLOUD_DATA_DIR}:z
      - /mnt/share:/mnt/share:z
    restart: always


  nextcloud-cron:
    image: nextcloud
    build: ${PWD}/
    entrypoint: /cron.sh
    env_file: ${PWD}/.env
    links:
      - db
      - redis
    volumes:
      - ${PWD}/data:/var/www/html:z
      - ${NEXTCLOUD_DATA_DIR}:${NEXTCLOUD_DATA_DIR}:z
      - /mnt/share:/mnt/share:z
    restart: always
