---
version: "3.8"
name: "gitlab"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: '${HOST}'
    env_file: ${PWD}/.env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${HOST}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${SSH_PORT}
        gitlab_rails['initial_root_password'] = "${PASSWORD}"
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${SSH_PORT}:22
    volumes:
      - '${PWD}/config:/etc/gitlab'
      - '${PWD}/logs:/var/log/gitlab'
      - '${PWD}/data:/var/opt/gitlab'
    shm_size: '256m'
    labels:
      - com.centurylinklabs.watchtower.enable=true
