---
# version: '3.9'
name: audiobooks
services:

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: always
    env_file: ${PWD}/.env
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${AUDIOBOOKS_FOLDER}:/audiobooks
      - ${BOOKS_FOLDER}:/books
      - ${PODCASTS_FOLDER}:/podcasts
      - ${PWD}/config:/config
      - ${PWD}/metadata:/metadata
    labels:
      - com.centurylinklabs.watchtower.enable=true
