---
# version: "3.3"
name: portainer-agent
services:

  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    env_file: ${PWD}/.env
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks: {}
