---
# version: "3.3"
name: portainer
services:

  portainer-ce:
    ports:
      - 8000:8000
      - 9000:9000
    container_name: portainer
    restart: always
    env_file: ${PWD}/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/portainer_data:/data
    image: portainer/portainer-ce:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks: {}
