---
version: "3.9"
name: libretranslate
services:

  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate
    restart: unless-stopped
    env_file: ${PWD}/.env
    ports:
      - ${WEB_PORT}:5000
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    command:  --api-keys --metrics --disable-files-translation
    volumes:
      - ${PWD}/db:/app/db
      - ${PWD}/data:/home/libretranslate/.local/share
      - ${PWD}/cache:/home/libretranslate/.local/cache
