---
version: '3.4'
name: 'node-exporter'
services:

   node-exporter:
    image: prom/node-exporter
    env_file: ${PWD}/.env
    environment:
      TZ: ${TZ}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - ${PORT}:9100
    restart: always
    networks:
      - default
