---
version: "3.8"
name: "dockge"
services:
  dockge:
    image: louislam/dockge
    restart: always
    env_file: ${PWD}/.env
    ports:
      - ${PORT}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data:/app/data
      - ${STACKS_PATH}:${STACKS_PATH}
    environment:
      - DOCKGE_STACKS_DIR=${STACKS_PATH}
    labels:
      - com.centurylinklabs.watchtower.enable=true
